"""init_web3_tables

Revision ID: 4d1f8c1ed16c
Revises: 
Create Date: 2026-03-27 00:18:09.174630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d1f8c1ed16c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odaily_news', 'is_valuable',
               existing_type=sa.BOOLEAN(),
               comment='是否有投资价值',
               existing_nullable=True)
    op.alter_column('odaily_news', 'sentiment',
               existing_type=sa.VARCHAR(length=20),
               comment='情绪倾向(positive/neutral/negative)',
               existing_nullable=True)
    op.alter_column('odaily_news', 'extracted_tokens',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='提取的代币列表',
               existing_nullable=True)
    op.alter_column('odaily_news', 'final_action',
               existing_type=sa.VARCHAR(length=20),
               comment='最终投资建议(buy/sell/hold/ignore)',
               existing_nullable=True)
    op.alter_column('odaily_news', 'final_reasoning',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='决策理由列表',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odaily_news', 'final_reasoning',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='决策理由列表',
               existing_nullable=True)
    op.alter_column('odaily_news', 'final_action',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='最终投资建议(buy/sell/hold/ignore)',
               existing_nullable=True)
    op.alter_column('odaily_news', 'extracted_tokens',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='提取的代币列表',
               existing_nullable=True)
    op.alter_column('odaily_news', 'sentiment',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='情绪倾向(positive/neutral/negative)',
               existing_nullable=True)
    op.alter_column('odaily_news', 'is_valuable',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否有投资价值',
               existing_nullable=True)
    # ### end Alembic commands ###
